[tool.poetry]
name = "pyarrow-stubs"
version = "10.0.1.2"
description = "Type annotations for pyarrow"
authors = ["ZhengYu, Xu <zen-xu@outlook.com>"]
license = "BSD-2-Clause"
homepage = "https://github.com/zen-xu/pyarrow-stubs"
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: BSD License",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering",
]
packages = [{ include = "pyarrow-stubs" }]

[tool.poetry.dependencies]
python = "^3.7,<3.11"

[tool.poetry.dev-dependencies]
black = ">=22.12.0"
isort = ">=5.10.1"
numpy = "1.21.4"
mypy = "^0.991"
pre-commit = ">=2.19.0"
pyarrow = "10.0.1"
pyright = ">=1.1.284"
pytest = ">=7.1.2"
typing-extensions = ">=4.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ['py37']

[tool.isort]
profile = "black"
combine_as_imports = true
force_grid_wrap = 2
force_sort_within_sections = true
